export const init = [
  {
    isDeleted: true,
    _id: "11",
    product_name: "Iklan 1",
    image: "https://placeimg.com/250/250/tech",
    price: 1000,
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      _id: "1",
      name: "Category 1",
      createdAt: new Date(),
      updatedAt: new Date(),
      __v: 0,
    },
    __v: 0,
  },
  {
    isDeleted: true,
    _id: "31",
    product_name: "Iklan 2",
    image: "https://placeimg.com/250/250/tech",
    price: 3000,
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      _id: "2",
      name: "Category 2",
      createdAt: new Date(),
      updatedAt: new Date(),
      __v: 0,
    },
    __v: 0,
  },
  {
    isDeleted: true,
    _id: "3",
    product_name: "Iklan 3",
    image: "https://placeimg.com/250/250/tech",
    price: 3000,
    createdAt: new Date(),
    updatedAt: new Date(),
    category: {
      _id: "3",
      name: "Category 3",
      createdAt: new Date(),
      updatedAt: new Date(),
      __v: 0,
    },
    __v: 0,
  },
];

export const categorys = [
  {
    _id: "1",
    name: "ATK",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "2",
    name: "HP",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "3",
    name: "Laptop",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];
