name: Testing
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Run unit-test
        run: npm run test
